### ISSUE TITLE
Lineup the xp and ranks gained graphs in the xp tracker

### ISSUE THREAD

**Issue by MagicfTail** [runelite/runelite.net#174]
The ranks gained has a total ranks while the xp gained doesn't. This means the two graphs don't line up, making it look weird
https://i.imgur.com/E1W4eJs.png

**Comment by deathbeam** [comment]
Well, the issue is that if I would show xp gained on side, the rest of bars will get very small

**Comment by deathbeam** [comment]
Unless you got all XP in 1 skill or so, but otherwise if you just sum the XP gained and you gained smaller amount of XP in all skills, or more than 1 skill, then there will be 1 giant bar at side and bunch of tiny ones next to it.

**Comment by MagicfTail** [comment]
Yeah, you're right. Just removing the total ranks would probably be a better solution.

**Comment by MagicfTail** [comment]
Or move it to the right instead so the misalignment is less noticeable

**Comment by deathbeam** [comment]
Well, the total ranks is sort of important information, as its different from other ranks gained (e.g its not just sum).

**Comment by MagicfTail** [comment]
I guess, idk then 🤷‍♀️

**Comment by deathbeam** [comment]
Yeah, no idea as well. It bothers me that it is not aligned too but idk how to solve it

**Comment by psikoi** [comment]
@deathbeam can be closed
