### ISSUE TITLE
Inform user last time he used RuneLite; If the data does not match with RuneScape's - display vital warning.

### ISSUE THREAD

**Issue by gccltl** [runelite/runelite.net#190]
_Suggestion_:

Inform user when the last time was RuneLite used & **display vital warning if the RuneLite's data does not match with RuneScape's "Last time you logged in was ..."**

_Why?_

Such feature could possibly be a life-saver for the user if his account was compromised, he could instantly know it. Not all intruders act immediatly,  so there's a chance for the user to review his RuneScape activity and act appropriately.

**Prototype of mine on how it could look like:**

![image](https://user-images.githubusercontent.com/28257966/52885114-cdcb4c80-3178-11e9-86aa-a79072b147f9.png)

**Comment by deathbeam** [comment]
I think you should maybe just turn to Jagex for this (any normal service just sends you email for any suspicious activity, e.g new PC etc), we can't make the tracker reliable enough so the information could provide any value.

**Comment by gccltl** [comment]
> I think you should maybe just turn to Jagex for this (any normal service just sends you email for any suspicious activity, e.g new PC etc), we can't make the tracker reliable enough so the information could provide any value.

Ohh, I only now realised I posted this to runelite.net repository, sorry.
Would you mind to transfer it?

But why you can't make a tracker reliable enough so the information could provide any value? 
You could sync the information with Google account.

**Comment by deathbeam** [comment]
Because you can play on the account on OSRS client/OSB, even mobile and we would have no way to sync that, and so instead we would just be constantly displaying false warnings, and then the information will lose any value.

**Comment by deathbeam** [comment]
I did not even noticed that you posted this in wrong repository, so relabeled the issue as invalid
