### ISSUE TITLE
XP Tracker Online shows 0 xp gained

### ISSUE THREAD

**Issue by bigwildo010** [runelite/runelite.net#193]
Online XP Tracker shows 0 xp and ranks but shows charts with labels.

When skill or total xp is right-clicked in XP Tracker addon and Open Online Tracker is selected, it opens my default browser (Chrome 71.0.3578.98) to the correct page, and it loads the skill list and X axes, but displays 0 gains for rank and xp charts. Clicking other skills or total on the left pane changes chart labels but not data (0s). I think this started in November 2018. I've also tried copy-pasting the URL into MS Edge (42.17134.1.0) to the same result. I'm running Windows 10 Pro x64. Runelite version 1.5.12. Launcher version 1.6.0. I saw another bug report #62 that details the same issue but for user names with underscores; my OSRS username is Bigwildo010, so this would not be the case.
Reposted here from runelite/runelite issue 7919 according to Nightfirecat's recommendation.

**Comment by deathbeam** [comment]
Client repo was correct place for this

**Comment by Nightfirecat** [comment]
My bad :sweat_smile:

**Comment by bigwildo010** [comment]
Didn't mean to call you out hahah
Thanks for the explanation deathbeam.
