### ISSUE TITLE
Sort items in loot tracker by highest value

### ISSUE THREAD

**Issue by fargoldbee** [runelite/runelite.net#213]
1. ~~Add the total value of all kills to the loot tracker on the site~~ implemented in #273 
2. Sort highest value items first like on the client

![image](https://user-images.githubusercontent.com/46892701/53587000-a36e8b80-3b89-11e9-89f7-bda646c07e49.png)
![image](https://user-images.githubusercontent.com/46892701/53586833-4d99e380-3b89-11e9-984d-795f7949b4c4.png)

**Comment by deathbeam** [comment]
First part of the issue was implemented in #273 so updated the description and title
