### ISSUE TITLE
Character listing on /account/home should use display names, not usernames/emails

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite.net#215]
Possible security issue for streamers, and also looks pretty ugly when longer email addresses overflow from the container

**Comment by yanikore** [comment]
In the background accounts could be tracked using a token which is derived from the username using a one-way hash.

**Comment by Adam-** [comment]
We don't actually have the display names, but we could modify the client to save them and associate them to the accounts. Storing a username hash might be harder due to backwards compatibility. Maybe once we get a more proper way of doing account-specific config we could do that?

**Comment by yanikore** [comment]
Backwards compatibility shouldn't be too hard if we can calculate the token both on the client and the server. I'd say we convert all usernames to tokens but keep the usernames for a limited amount of time while everybody switches over to the new version.
