### ISSUE TITLE
Ability to export collection log as JSON

### ISSUE THREAD

**Issue by gc** [runelite/runelite.net#229]
This is in reference to the ingame feature: https://oldschool.runescape.wiki/w/Collection_log

Suggestion: Allow the user to sync their collection log to the website (even if they have to click on tabs for the  client to retrieve the data), it would appear something like this: 
![chrome_2019-03-24_15-11-54](https://user-images.githubusercontent.com/30398469/54874837-3035fd80-4e47-11e9-8aac-ea4b0d6b1b9d.png)

It would have many uses, for example: something like http://ironmanosrs.com could use it to automatically load in all your items (maybe even integrated into the runelite site, so you can link people to `runelite.net/collection/:name` and they can see your collection in the same format as ironmanosrs.com), and just in the same nature of the loot tracker, so you can look at and enjoy your achievements.

**Comment by evelez7** [comment]
Is this something the maintainers would be open to integrating? I'd love to look into this or #143 and deliver, but I want to make sure it is possible in regards to API load, scope, etc.

**Comment by Adam-** [comment]
We don't store the collection log in the config at all, so we'd have to do that first at least. I think there is one or more plugin hub plugins that already have this functionality though.

**Comment by evelez7** [comment]
[This plugin](https://runelite.net/plugin-hub/show/collection-log) enhances the native interface, exports a file, and uploads to its own site, but this issue also brings up a Runelite-supported interface for the collection similar to how the Grand Exchange log or loot list is implemented. This seems worthwhile to me.

**Comment by Nightfirecat** [comment]
I feel this is already solved well by that plugin. A majority of players who are interested in having collection log data stored to their config already use this plugin, and most other players don't care about having that available at any time.
