### ISSUE TITLE
Xeric's Talisman - Xeric's Glade teleportation icon misplaced

### ISSUE THREAD

**Issue by RRickkert** [runelite/runelite.net#244]
After the latest runescape update, the xeric's glade teleport has been moved. The map icon hasn't been updated yet.
![image](https://user-images.githubusercontent.com/38819529/58252238-e5ad0080-7d65-11e9-83d6-699d1eb8dfc6.png)
![image](https://user-images.githubusercontent.com/38819529/58252111-9ff03800-7d65-11e9-81d7-41546f8dda85.png)

**Comment by Adam-** [comment]
This belongs on the runelite/runelite repo, not the website.
