### ISSUE TITLE
Black screen when opening RuneLite on Mac 

### ISSUE THREAD

**Issue by emm3033** [runelite/runelite.net#298]
Every time I open RuneLite after an update I can't get the to the login because it's a black screen. I can still use the sidebar with the plugins but nothing else. I am on a MacOS High Sierra version 10.13.6. RuneLite is updated to 1.6.5. What can I do to fix this issue?

**Comment by Nightfirecat** [comment]
This is the wrong repository for this bug to be reported. Please re-open this issue on https://github.com/runelite/runelite
