### ISSUE TITLE
Loot Tracker Values on website are different to client

### ISSUE THREAD

**Issue by Emziie** [runelite/runelite.net#308]
Large price difference from website to Client

![image](https://user-images.githubusercontent.com/61770055/75844208-3b223d80-5dcd-11ea-80de-9feda454fced.png)
![image](https://user-images.githubusercontent.com/61770055/75844217-42494b80-5dcd-11ea-8aaf-575baea5daee.png)

**Comment by Geenzo** [comment]
Noted items seem to be skipped on the response from GET `https://api.runelite.net/runelite-1.6.9/item/prices.js`
![image](https://user-images.githubusercontent.com/6834228/76132932-672c0180-600d-11ea-9336-7d0f3a3f39a4.png)
