### ISSUE TITLE
Add missing plugins to features

### ISSUE THREAD

**Issue by devLotto** [runelite/runelite.net#31]
Plugins that maybe should be added:

* Left-click option swapping (MenuEntrySwapperPlugin)
* HP and special attack regeneration meter
* Herbiboar plugin - next release
* Prayer reordering - next release
* Extend "Cannon" to "Displays the amount of cannonballs left in your cannon, along with common cannon spots."? - next release

**Comment by sethtroll** [comment]
I usually add the features from the snapshot the night before a release
