### ISSUE TITLE
grand exchange feature displays wrong icon for dragon hunter crossbow

### ISSUE THREAD

**Issue by 000000653** [runelite/runelite.net#318]
I'm terrible at titles, sorry :P.

Currently, in the grand exchange feature, if you have a dragon hunter crossbow in your history, it displays the old, pre-15th November 2018, icon. As seen here:
![](https://cdn.discordapp.com/attachments/419891709883973642/703862765898694696/chrome_7dxoAkqnq9.png)

Inspect tool tells me it's displaying [this link](https://services.runescape.com/m=itemdb_oldschool/obj_big.gif?id=21012) when it should be displaying [this link](https://services.runescape.com/m=itemdb_oldschool/1587637813166_obj_big.gif?id=21012)

**Comment by deathbeam** [comment]
I am not sure if this is even fixable (or how am i supposed to get that magic number in second link) without hardcoding it.

**Comment by 000000653** [comment]
Jagex seems to have fixed this, wowee
