### ISSUE TITLE
Remove login account name from runelite.net

### ISSUE THREAD

**Issue by claythearc** [runelite/runelite.net#326]
Would it be possible to remove login names from the page at https://runelite.net/account/home and instead replace with current Display Names or something similar? Feels kinda needlessly insecure to  store them as login names vs something else.

**Comment by loldudester** [comment]
Afaik login names are the only unique identifier we have for a Runescape account. If you changed your display name, you'd want the data to track over that change, so we'd have to store the login name in the back-end anyway. Since that page is only visible to you anyway, I don't see how this is insecure.

**Comment by Nightfirecat** [comment]
Related to runelite/runelite#8050. Whenever we get around to using some identifier which is not personally identifying, we would no longer be able to do display your login name on the website when logged in anyway.

**Comment by claythearc** [comment]
The issue is in the event of account compromise, your login name becomes visible to the person who now has access - which can lead to issues such as brute forcing the login page. While this is unlikely to result in an account being compromised, it can be used to DOS you via the login limit, preventing logins on that account - even with 2FA enabled.

Would it not be possible to track via some hash on the back end, and then update based on that, with an additional column referencing the current display name?

**Comment by Nightfirecat** [comment]
Display name is also a personally identifying piece of information which, I'm sure for many players, would also point a would-be attacker toward some other source of their data to attempt to breach, so I can't say we'd implement anything like that. As of yet, we haven't come to a clear consensus on what exactly this kind of hashing or tokenization would look like once completed.
