### ISSUE TITLE
Plugin-hub page search broken on Safari

### ISSUE THREAD

**Issue by Broooklyn** [runelite/runelite.net#349]
Tested on Safari 13.1 and 14.0 on macOS and Safari on iOS 14

No plugins show when loading the page, and the search bar does not function despite being able to type in the field.

There were no errors in the console log, so I'm not really sure what's up.  
<img width="1020" alt="Screen Shot 2020-08-14 at 1 01 56 PM" src="https://user-images.githubusercontent.com/54762282/90276777-7754d200-de32-11ea-8502-f66be06c4d02.png">

**Comment by arthurtyukayev** [comment]
@deathbeam This unicode parsing isn't working on Safari, any ideas why this is so complicated? Why isn't there simply a manifest.json file in the repo instead of a JS file?

https://github.com/runelite/runelite.net/blob/master/src/modules/plugin-hub.js#L25
