### ISSUE TITLE
Paginate GE trade history

### ISSUE THREAD

**Issue by Adam-** [runelite/runelite.net#355]
With users with a lot of trades the GE page takes a very long time to build, which is primarily a UI heavy task.

**Comment by psikoi** [comment]
Is this a purely rendering issue? Is the data fetching fast enough? I can work on it

**Comment by arthurtyukayev** [comment]
Does the API support pagination?

**Comment by deathbeam** [comment]
Depending on implementation this might break search what would be pretty annoying, so if possible the data should still be fetched in background and the ui paginated

**Comment by joey-colon** [comment]
i'll take a stab at this 🤠
