### ISSUE TITLE
Latest Update Broke Key Remapping

### ISSUE THREAD

**Issue by NightmareSHW** [runelite/runelite.net#377]
I'm not sure if it is something different within Runelite or something that happened to the game client, but I used to be able to press the numpad buttons on the side of my mouse and they would function as F-Keys, numbers, and menu/dialogue options. For example, my Numpad-1 key is bound to Spacebar, but no longer functions as a "1" when in a menu or dialogue, whereas it used to before.

**Comment by arthurtyukayev** [comment]
Wrong repo.
