### ISSUE TITLE
XP Tracker is squished on mobile

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite.net#39]
Tried it on two browsers, same issue. The whole site should probably be double checked for mobile friendliness, but especially the xp tracker I see people wanting on their phones while they're playing on their pc.

![screenshot 1](https://cdn.discordapp.com/attachments/419891709883973642/428777125022138378/Screenshot_20180329-004641.png)

![screenshot 2](https://cdn.discordapp.com/attachments/419891709883973642/428777559379935235/Screenshot_20180329-004842.png)

**Comment by deathbeam** [comment]
Can you try again? I did some changes to xp tracker on mobile and it should be better now.

**Comment by ShaunDreclin** [comment]
Has the address changed? Getting a 404 now

**Comment by sethtroll** [comment]
https://runelite.net/xp/show/fishing/deathbeam/1week/now

**Comment by ShaunDreclin** [comment]
Ahh nice yeah it's more readable now, though I think I would hide the list of skills in an overlay menu of some sort rather than having to scroll up and down between the list and graphs

**Comment by deathbeam** [comment]
This should be resolved now. For the different layout for the sidebar, open up separate feature request
