### ISSUE TITLE
Loot export LootAggregate is missing optional fields

### ISSUE THREAD

**Issue by me0w1** [runelite/runelite.net#432]
If you export loot data from https://runelite.net/ the returned loot-tracker.json constains LootAggregate for each entry as per https://static.runelite.net/api/http-service/. Currently exported jsons are missing optional fields first_time, last_time and amount.

Is missing optional fields first_time, last_time and amount intentional? Could there be option to choose if those are included or not if it is intentional?

Expected: exporeted LootAggregate fields are filled
Obseverd: some of optional fields are missing and theres no way to include them

**Comment by DustinsCode** [comment]
Would these fields be okay to just add to the loot tracker export, or should there be some sort of field to check to add the optional fields?

**Comment by deathbeam** [comment]
Loot tracker format changes so I dont think this matters anymore (and im including all data now in raw export anyway)
