### ISSUE TITLE
Suggestion: Add an addition to the Menu Entry Swapper plug-in that allows for left-click Build and Remove in your POH.

### ISSUE THREAD

**Issue by Krill7** [runelite/runelite.net#439]
I feel like this would be very helpful and save people a lot of time. Very similar to a lot of other options this plug-in provides!

**Comment by Bram91** [comment]
This would go directly against the following rule:
> Modifies menu options for construction, such as prioritising build/remove options

https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1

**Comment by deathbeam** [comment]
Wrong repo as bram said
