### ISSUE TITLE
Logo redesign suggestion

### ISSUE THREAD

**Issue by psikoi** [runelite/runelite.net#44]
After showing my website designs to the #development channel on the runelite discord, we all started bouncing ideas off of eachother trying to come up with logo ideas.

Runelite should have atleast three types of logos:
- Type
- Icon
- Type + slogan

I have provided a light and dark example of each (to be used on different backgrounds)

I'd love some feedback so that we can all work together to make it happen.

After a lot of discussion, here's a few suggestions I came up with:

![logos](https://user-images.githubusercontent.com/3278148/38272071-167f2f6c-3780-11e8-9732-c1b793731dc2.png)

EDIT: added two more variants to the icons:

![5b56d3327e85d7be17d120f4e91b7d44](https://user-images.githubusercontent.com/3278148/38272952-acc5baf2-3782-11e8-8554-4098e705e87a.png)

**Comment by ShaunDreclin** [comment]
I dig it! I'd say D for the main one and E for icons

**Comment by Infinitay** [comment]
A and B have my votes. The white background gives life to "lite" in RuneLite to me by being simplistic. Additionally, as much as I love dark themes, I think too many existing clients use them, primarily OSB and RuneLoader would be my second example.

If we're going for the clean, simple approach, I'd vote for A, but to be honest, reminding the user we're open source isn't a bad idea, and gives it a sense of professionalize to me

**Comment by MESLewis** [comment]
I like the slogan under the logo, doesn't have to go everywhere but I agree with Infinitay that it's good to put that out there as a feature. It may be our biggest difference between other clients.

**Comment by psikoi** [comment]
Added two more varients to the icon on the original post.

![5b56d3327e85d7be17d120f4e91b7d44](https://user-images.githubusercontent.com/3278148/38272937-a02c4202-3782-11e8-92b6-752e801d9882.png)

**Comment by gccltl** [comment]
Any updates over this? Will obsidian rebranding ever come out?

**Comment by devLotto** [comment]
Our current logo is good for now. It would be nice if someone could make an identical-looking vector graphics version of our current logo, so it can be upscaled without losing detail.

**Comment by devLotto** [comment]
And a full "RuneLite" version of our current logo would be nice to have too.

**Comment by deathbeam** [comment]
Noone started making t-shirts yet so there is still time to change it! :D

**Comment by ShaunDreclin** [comment]
I'm still 100% in favour of ditching the rs3-style logo haha

**Comment by psikoi** [comment]
If we were to change it it would have to be similar to the current, but a vector version would be great to have

**Comment by deathbeam** [comment]
I guess it is way too late to redesign logo so closing the issue (and we already went with both client and website redesign without changing logo).
