### ISSUE TITLE
Homepage download button dropdown scales incorrectly at high width

### ISSUE THREAD

**Issue by deadmeu** [runelite/runelite.net#477]
When zooming out or making the page wide the dropdown element next to the download button shrinks, while the download button stays the same size.
![image](https://user-images.githubusercontent.com/12111013/201276019-d0e0f980-9e6f-46d8-bd98-76015763c2e8.png)
I have an ultrawide monitor and easily noticed this but even on a regular 1440p display you can tell the heights don't match.
![image](https://user-images.githubusercontent.com/12111013/201276380-937a9d92-3206-4f6b-8e47-b879e4671b0d.png)

**Comment by Nightfirecat** [comment]
This has nothing to do with the zoom level, but to do with the styles being broken at high widths (>2500px it seems)

**Comment by Nightfirecat** [comment]
Fixed in fce2bb788ce670b044e9bd5974a4c3ec231a1e29
