### ISSUE TITLE
Distinguish between account types (Iron/Hardcore/Ultimate) on the XP tracker.

### ISSUE THREAD

**Issue by SomeZer0** [runelite/runelite.net#51]
For example, on my Ironman, the site says I gained +10,000 ranks this week, where CML shows I only gained 750.
This is because CML pulls ranks gained on the Ironman highscores, and RL XP tracker pulls ranks gained on the vanilla highscores.

**Comment by deathbeam** [comment]
Blocked by https://github.com/runelite/runelite/issues/6681

**Comment by psikoi** [comment]
@deathbeam I think should be closed
