### ISSUE TITLE
Download fails on Firefox on MacOS, works fine in Safari

### ISSUE THREAD

**Issue by LucianoLaratelli** [runelite/runelite.net#67]
Firefox version: 60.0.1 (64-bit)
macOS High Sierra Version 10.13.4 (17E202)
Safari Version 11.1 (13605.1.33.1.4)

Not sure if this is a server issue or something locally, figured I'd let you folks know. Thanks for the great program!

**Comment by Adam-** [comment]
The downloads a hosted on GitHub releases - which is hosted on s3... so I doubt that it is something wrong on their end. It works for me now.

**Comment by deathbeam** [comment]
This cant really be related to either runelite or website, closing as wontfix
