### ISSUE TITLE
RuneLite detecting as "desktop" for Nvidia instant replay...

### ISSUE THREAD

**Issue by pullup** [runelite/runelite.net#73]
Any idea why it doesn't see RuneLite as a game and enable instant replay?

It would be sick if you guys could fix that and also integrade Nvidia highlights for kills and deaths and stuff, would make this the standout video maker client IMO. ( https://developer.nvidia.com/Highlights )

**Comment by deathbeam** [comment]
Wrong repo, reopen here if necessary: https://github.com/runelite/runelite
